### PR TITLE
Fix dart2native compile command

### PR DESCRIPTION
**Pull request by xvld**

### CODE REVIEW

**Comment by xvld** [comment]
Hey, can this be merged? @j4qfrost

**Comment by j4qfrost** [comment]
I'm just going to go ahead and merge this and fix releases later. Really sorry for the wait.

**Comment by srmanc** [comment]
When is this going to be released? Is there a way to build conduit locally from master?

**Comment by j4qfrost** [comment]
I'll just cave and release it later today. I've been trying to fix the way conduit pulls the dependencies in my free time, but I haven't really figured it out yet. The issue makes releases with melos incredibly difficult and breaks some of the testing.

**Pull request merged**
